#!/usr/bin/env python3
"""Put a content hash on every local CSS/JS URL so a deploy is picked up at once.

GitHub Pages serves these with Cache-Control: max-age=600, and iOS in practice
holds them a good deal longer than that. The symptom is not subtle: a change
ships, the site is verifiably correct on a fresh load, and the phone that was
looking at it ten minutes ago keeps rendering the old stylesheet with no way to
tell that it is doing so. It cost a whole round of "it's not there" / "it is
there, here is the line on main" before anyone thought to suspect the cache.

A browser caches by URL, so /app.css?v=9f2a1c07 and /app.css?v=3b81ee45 are two
different resources and the second cannot be served from a copy of the first.
The hash is of the file's own bytes, so it changes exactly when the file does
and never otherwise -- no version to bump by hand and nothing to forget.

Run with no arguments to rewrite; --check exits 1 if anything is out of date,
which is what CI uses to notice an asset changed without its URL following.

Deliberately NOT stamped: glossary.html and items.html. Both are generated by
scripts that have their own --check modes comparing the committed file against
what the generator produces, and a stamp this script added would be a
difference those checks would report as drift on every run. They also load
neither app.css nor app.js, so they are not where this problem lives.
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Hand-written pages, plus the prerendered item pages, which are copies of
# index.html and so inherit its stamps on the next prerender anyway -- they are
# rewritten here too so they are correct in the meantime rather than a week
# behind.
PAGES = ["index.html", "flip-history.html", "runelite-plugin.html",
         "flipping-guide.html"]

# href="..." or src="..." pointing at a local .css/.js, with or without a stamp
# already on it. The (?:\?v=[0-9a-f]+)? is what makes this idempotent: running
# it twice replaces the old hash rather than appending a second one.
REF = re.compile(r'((?:href|src)=")([^"?\s]+\.(?:css|js))(?:\?v=[0-9a-f]+)?(")')


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:8]


def resolve(url: str, page: Path) -> Path | None:
    """Where a URL in `page` lands on disk. Absolute URLs are site-root
    relative; everything else is relative to the page itself. Anything that
    escapes the repo or does not exist is left alone rather than guessed at."""
    if url.startswith(("http://", "https://", "//", "data:")):
        return None
    target = (ROOT / url.lstrip("/")) if url.startswith("/") else (page.parent / url)
    try:
        target = target.resolve()
        target.relative_to(ROOT)
    except (OSError, ValueError):
        return None
    return target if target.is_file() else None


def stamp(page: Path, cache: dict) -> tuple[str, int]:
    src = page.read_text()
    hits = 0

    def sub(m):
        nonlocal hits
        head, url, tail = m.groups()
        target = resolve(url, page)
        if target is None:
            return m.group(0)
        if target not in cache:
            cache[target] = digest(target)
        hits += 1
        return f"{head}{url}?v={cache[target]}{tail}"

    return REF.sub(sub, src), hits


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any page's stamps are out of date")
    args = ap.parse_args()

    pages = [ROOT / p for p in PAGES if (ROOT / p).is_file()]
    pages += sorted((ROOT / "item").glob("*/index.html"))
    if not pages:
        sys.exit("no pages found — run me from the repo root")

    cache: dict = {}
    stale, written, refs = [], 0, 0
    for page in pages:
        out, hits = stamp(page, cache)
        refs += hits
        if out == page.read_text():
            continue
        if args.check:
            stale.append(page.relative_to(ROOT).as_posix())
        else:
            page.write_text(out)
            written += 1

    if args.check:
        if stale:
            print("asset stamps are out of date in %d page(s):" % len(stale))
            for p in stale[:10]:
                print("  " + p)
            if len(stale) > 10:
                print("  … and %d more" % (len(stale) - 10))
            print("run: python3 stamp_assets.py")
            sys.exit(1)
        print("asset stamps are current (%d refs across %d pages)" % (refs, len(pages)))
        return

    for target, h in sorted(cache.items()):
        print("  %-18s %s" % (target.name, h))
    print("stamped %d refs across %d pages (%d rewritten)" % (refs, len(pages), written))


if __name__ == "__main__":
    main()
